FROM kalilinux/kali-rolling

WORKDIR /root

ARG DEBIAN_FRONTEND=noninteractive

RUN apt -y update && apt -y dist-upgrade && apt -y autoremove && apt clean

## General
RUN apt -y install python3-pip golang git
RUN apt -y install openssh-server nmap wordlists seclists

## Directory enumeration
RUN apt -y install dirb gobuster ffuf

## Technology scanner
RUN pip3 install wappy

## Vulnerability scanner
RUN apt -y install nikto nuclei whatweb

## CMS scanner
RUN apt -y install wpscan cmseek

## TLS/SSL scanner
RUN apt -y install testssl.sh sslscan

# Install non-package tools
WORKDIR /opt

RUN git clone https://github.com/dariusztytko/vhosts-sieve.git && \
    pip3 install -r vhosts-sieve/requirements.txt && \
    chmod +x vhosts-sieve/vhosts-sieve.py && \
    ln -s /opt/vhosts-sieve/vhosts-sieve.py /usr/local/bin/vhosts-sieve

RUN go install github.com/projectdiscovery/katana/cmd/katana@latest && \
    ln -s /root/go/bin/katana /usr/local/bin/

WORKDIR /root

## Configure SSH service with public key
COPY ./config ./config
RUN mkdir -p ./.ssh/ && cat ./config/id_rsa.pub > ./.ssh/authorized_keys && rm -rf ./config/ && mkdir /var/run/sshd

EXPOSE 22

ENTRYPOINT ["/usr/sbin/sshd", "-D"]
